### ISSUE TITLE
Is not working

### ISSUE THREAD

**Issue by betax96** [kotvertolet/youtube-jextractor#12]
An exception appears when extracting any video

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extractYoutubeVideoData(YoutubeJExtractor.java:80)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extract(YoutubeJExtractor.java:50)
```

**Comment by kotvertolet** [comment]
Yep, I've noticed too, youtube made some changes again, I'll fix it ASAP.

**Comment by graffiti75** [comment]
This exception is happening with me, too.
