### ISSUE TITLE
It does not work in some videos

### ISSUE THREAD

**Issue by betax96** [kotvertolet/youtube-jextractor#2]
It does not work in some videos, when trying to extract the information from the video it gives an exception.

`java.lang.NullPointerException
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extractAdaptiveFormatsData(YoutubeJExtractor.java:72)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.getYoutubeVideoData(YoutubeJExtractor.java:62)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extract(YoutubeJExtractor.java:36)
        at com.btxdev.ytdltest.MainActivity$1.run(MainActivity.java:24)`

The video is not blocked in my country and I can see it normally from youtube.

This is the video:
https://www.youtube.com/watch?v=XcicOBS9mBU

**Comment by kotvertolet** [comment]
Thanks for the issue, you've pointed me to the problem in my implementation and I'm gonna fix it, hold on :)

**Comment by kotvertolet** [comment]
@betax96 fixed, please check on 0.1.4 version
