### ISSUE TITLE
'java.lang.String okhttp3.ResponseBody.string()' on a null object reference

### ISSUE THREAD

**Issue by mjjisan** [kotvertolet/youtube-jextractor#30]
2020-06-13 00:59:50.375 19894-19894/com.doracone.dorafy E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.doracone.dorafy, PID: 19894
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.ResponseBody.string()' on a null object reference
        at com.doracone.dorafy.Until.YoutubeJExtractor.extractYoutubeVideoData(YoutubeJExtractor.java:114)
        at com.doracone.dorafy.Until.YoutubeJExtractor.extractAndPrepareVideoData(YoutubeJExtractor.java:100)
        at com.doracone.dorafy.Until.YoutubeJExtractor.extract(YoutubeJExtractor.java:86)
        at com.doracone.dorafy.Adapter.VideoAdapter$1.onClick(VideoAdapter.java:76)
        at android.view.View.performClick(View.java:5675)
        at android.view.View$PerformClick.run(View.java:22641)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by kotvertolet** [comment]
Thanks for posting the issue, looking into it now.

**Comment by mjjisan** [comment]
;)

**Comment by mjjisan** [comment]
please fixed immediately because of my project pending...

**Comment by mjjisan** [comment]
![play](https://user-images.githubusercontent.com/15358680/84564132-8e1f6f80-ad82-11ea-951a-dfa51dcefde1.png)

**Comment by kotvertolet** [comment]
@mjjisan I was unable to reproduce it, please provide more details of how to reproduce it
ps: if you wanna some problem fixed **immediately** feel free to fix it by yourself (this is open source, mate!  😄) and push it via pull request, I'm not always availble to do that because I'm not 24/7 at my workstation ))

**Comment by mjjisan** [comment]
please take your time and fixed it.. i will wait for fixing

**Comment by mjjisan** [comment]
2020-06-13 23:44:38.179 13751-13751/com.doracone.dorafy D/OkHttp: --> GET https://www.youtube.com/watch?v=gq9w14ag0ls&gl=US&has_verified=1&bpctr=9999999999
2020-06-13 23:44:38.258 13751-13751/com.doracone.dorafy D/libc-netbsd: getaddrinfo: www.youtube.com get result from proxy gai_error = 0
2020-06-13 23:44:38.260 13751-13751/com.doracone.dorafy I/System.out: [socket][1] connection www.youtube.com/172.217.167.142:443;LocalPort=-1(10000)
2020-06-13 23:44:38.562 13751-13751/com.doracone.dorafy I/System.out: [socket][/10.59.169.138:59001] connected
2020-06-13 23:44:39.270 13751-13751/com.doracone.dorafy D/OkHttp: <-- 429 Too Many Requests https://www.youtube.com/watch?v=gq9w14ag0ls&gl=US&has_verified=1&bpctr=9999999999 (1090ms, 49429-byte body)
2020-06-13 23:44:39.508 13751-13751/com.doracone.dorafy D/AndroidRuntime: Shutting down VM

**Comment by mjjisan** [comment]
https://www.youtube.com/watch?v=gq9w14ag0ls&gl=US&has_verified=1&bpctr=999999999
when i check postman this url to get method then i found html page there ar all information but when use my app then cash and log Attempt to invoke virtual method 'java.lang.String okhttp3.ResponseBody.string()' on a null object reference

**Comment by mjjisan** [comment]
Hey i'm found where is problem ... please see picture in mark like there is problem.
this problem is body get is null object
please fixed this please 


![Capture](https://user-images.githubusercontent.com/15358680/84577185-f2225200-addb-11ea-9b6c-b6ca8142e945.PNG)

**Comment by kotvertolet** [comment]
@mjjisan wait a second, I see you are using 'gq9w14ag0ls' as video id? If so I can't reproduce your problem on my side with the same video id. Ofcourse I can check if body is null and if so throws some exeption, but the question is why this problem occures on your side?
![](https://i.ibb.co/qNrFBgF/Screenshot-1.jpg)
