### ISSUE TITLE
Problem with youtubeJExtractor.extract()

### ISSUE THREAD

**Issue by Cioscos** [kotvertolet/youtube-jextractor#33]
Hi! I want to extract info about video and I've done:
```java
youtubeJExtractor.extract(videoId, new JExtractorCallback() {
                    @Override
                    public void onSuccess(YoutubeVideoData videoData) {
                        infoTv.setText(videoData.getVideoDetails().toString());
                    }

                    @Override
                    public void onNetworkException(YoutubeRequestException e) {
                        infoTv.setText(e.getMessage());
                    }

                    @Override
                    public void onError(Exception exception) {
                        infoTv.setText(exception.getMessage());
                    }
                });
```
Now as videoId I don't understand if I've to give the entire link or just the ID of the video that should be the last part of the link, but in any case it doesn't works.

### This is the stackTrace:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.yuotube_downloader, PID: 8580
    android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        at java.net.InetAddress.getAllByName(InetAddress.java:1152)
        at okhttp3.Dns$-CC.lambda$static$0(Dns.java:39)
        at okhttp3.-$$Lambda$Dns$mTkNcZf2K4euny3_jks6Cac6Az0.lookup(Unknown Source:0)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:135)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:187)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.github.kotvertolet.youtubejextractor.network.UserAgentInterceptor.intercept(UserAgentInterceptor.java:20)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:97)
        at com.github.kotvertolet.youtubejextractor.network.RequestExecutor.executeWithRetry(RequestExecutor.java:21)
        at com.github.kotvertolet.youtubejextractor.network.YoutubeSiteNetwork.getYoutubeVideoPage(YoutubeSiteNetwork.java:51)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extractYoutubeVideoData(YoutubeJExtractor.java:112)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extractAndPrepareVideoData(YoutubeJExtractor.java:98)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extract(YoutubeJExtractor.java:84)
        at com.example.yuotube_downloader.MainActivity$1.onClick(MainActivity.java:38)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by kotvertolet** [comment]
@Cioscos  Hi Claudio! You tried to make a network call from a main thread which is prohibited by the android os, that's why you've got a **android.os.NetworkOnMainThreadException**.  You have to call .extract() method from a background thread using AsyncTask for example.

**Comment by Cioscos** [comment]
> @Cioscos  Hi Claudio! You tried to make a network call from a main thread which is prohibited by the android os, that's why you've got a **android.os.NetworkOnMainThreadException**.  You have to call .extract() method from a background thread using AsyncTask for example.

Thank you! I was searching on internet and I found the same conclusion. I create an AsyncTask and I solve the problem. You can close the Issue :)
