### ISSUE TITLE
is not working

### ISSUE THREAD

**Issue by betax96** [kotvertolet/youtube-jextractor#34]
org.mozilla.javascript.EvaluatorException: missing ] after element list
        at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
        at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:64)
        at org.mozilla.javascript.Parser.addError(Parser.java:260)
        at org.mozilla.javascript.Parser.reportError(Parser.java:328)
        at org.mozilla.javascript.Parser.reportError(Parser.java:315)
        at org.mozilla.javascript.Parser.reportError(Parser.java:308)
        at org.mozilla.javascript.Parser.arrayLiteral(Parser.java:3212)
        at org.mozilla.javascript.Parser.primaryExpr(Parser.java:3022)
        at org.mozilla.javascript.Parser.memberExpr(Parser.java:2655)
        at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2553)
        at org.mozilla.javascript.Parser.mulExpr(Parser.java:2477)
        at org.mozilla.javascript.Parser.addExpr(Parser.java:2461)
        at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2442)
        at org.mozilla.javascript.Parser.relExpr(Parser.java:2417)
        at org.mozilla.javascript.Parser.eqExpr(Parser.java:2389)
        at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2378)
        at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2367)
        at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2356)
        at org.mozilla.javascript.Parser.andExpr(Parser.java:2345)
        at org.mozilla.javascript.Parser.orExpr(Parser.java:2334)
        at org.mozilla.javascript.Parser.condExpr(Parser.java:2298)
        at org.mozilla.javascript.Parser.assignExpr(Parser.java:2254)
        at org.mozilla.javascript.Parser.variables(Parser.java:2091)
        at org.mozilla.javascript.Parser.statementHelper(Parser.java:1194)
        at org.mozilla.javascript.Parser.statement(Parser.java:1109)
        at org.mozilla.javascript.Parser.parseFunctionBody(Parser.java:746)
        at org.mozilla.javascript.Parser.function(Parser.java:916)
        at org.mozilla.javascript.Parser.primaryExpr(Parser.java:3018)
        at org.mozilla.javascript.Parser.memberExpr(Parser.java:2655)
        at org.mozilla.javascript.Parser.unaryExpr(Parser.java:2553)
        at org.mozilla.javascript.Parser.mulExpr(Parser.java:2477)
        at org.mozilla.javascript.Parser.addExpr(Parser.java:2461)
        at org.mozilla.javascript.Parser.shiftExpr(Parser.java:2442)
        at org.mozilla.javascript.Parser.relExpr(Parser.java:2417)
        at org.mozilla.javascript.Parser.eqExpr(Parser.java:2389)
        at org.mozilla.javascript.Parser.bitAndExpr(Parser.java:2378)
        at org.mozilla.javascript.Parser.bitXorExpr(Parser.java:2367)
        at org.mozilla.javascript.Parser.bitOrExpr(Parser.java:2356)
        at org.mozilla.javascript.Parser.andExpr(Parser.java:2345)
        at org.mozilla.javascript.Parser.orExpr(Parser.java:2334)
        at org.mozilla.javascript.Parser.condExpr(Parser.java:2298)
        at org.mozilla.javascript.Parser.assignExpr(Parser.java:2254)
        at org.mozilla.javascript.Parser.assignExpr(Parser.java:2277)
        at org.mozilla.javascript.Parser.expr(Parser.java:2233)
        at org.mozilla.javascript.Parser.nameOrLabel(Parser.java:1986)
        at org.mozilla.javascript.Parser.statementHelper(Parser.java:1240)
        at org.mozilla.javascript.Parser.statement(Parser.java:1109)
        at org.mozilla.javascript.Parser.parse(Parser.java:648)
        at org.mozilla.javascript.Parser.parse(Parser.java:583)
        at org.mozilla.javascript.Context.compileImpl(Context.java:2530)
        at org.mozilla.javascript.Context.compileString(Context.java:1515)
        at org.mozilla.javascript.Context.compileString(Context.java:1504)
        at org.mozilla.javascript.Context.evaluateString(Context.java:1259)
        at com.github.kotvertolet.youtubejextractor.utils.DecryptionUtils.decryptSignature(DecryptionUtils.java:38)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.decryptYoutubeStreams(YoutubeJExtractor.java:205)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extractAndPrepareVideoData(YoutubeJExtractor.java:101)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extract(YoutubeJExtractor.java:75)

**Comment by kotvertolet** [comment]
Thanks for reporting, I'm working on it

**Comment by kotvertolet** [comment]
@betax96 Fixed in 0.3.1, please check

**Comment by betax96** [comment]
ok it seems to be working fine now
