### ISSUE TITLE
it stopped working again

### ISSUE THREAD

**Issue by betax96** [kotvertolet/youtube-jextractor#50]
com.github.kotvertolet.youtubejextractor.exception.ExtractionException: Extraction failed. Please, report here: https://github.com/kotvertolet/youtube-jextractor/issues. Error details: No js video player url found
        at com.github.kotvertolet.youtubejextractor.utils.YoutubePlayerUtils.getJsPlayerUrl(YoutubePlayerUtils.java:41)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.decryptYoutubeStreams(YoutubeJExtractor.java:246)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extractAndPrepareVideoData(YoutubeJExtractor.java:150)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extract(YoutubeJExtractor.java:83)

**Comment by kotvertolet** [comment]
@betax96 hi! check new 0.3.3 version, sorry for the delay, I was ill
