### ISSUE TITLE
No js video player url found

### ISSUE THREAD

**Issue by rjhsolution** [kotvertolet/youtube-jextractor#51]
Error details: No js video player url found
at com.github.kotvertolet.youtubejextractor.utils.YoutubePlayerUtils.getJsPlayerUrl(YoutubePlayerUtils.java:41)
at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.decryptYoutubeStreams(YoutubeJExtractor.java:246)
at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extractAndPrepareVideoData(YoutubeJExtractor.java:150)
at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extract(YoutubeJExtractor.java:83)
at com.github.kotvertolet.youtubejextractor.ExtractionTests.checkMuxedStreamNonEncrypted(ExtractionTests.java:104)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)

**Comment by thehasnism** [comment]
yeah I'm facing this problem too. any solution?

**Comment by wingchunna** [comment]
I'm facing this problem too !

**Comment by SufyanQadeer** [comment]
yeah, I'm facing this problem too. any solution?

**Comment by kotvertolet** [comment]
Sorry guys I was ill, will fix it ASAP

**Comment by graffiti75** [comment]
I also got this error.

**Comment by kotvertolet** [comment]
@graffiti75  @SufyanQadeer @thehasnism  hi! check new 0.3.3 version, sorry for the delay, I was ill
