### ISSUE TITLE
Extraction failed. Please, report here: https://github.com/kotvertolet/youtube-jextractor/issues. Error details: Cannot extract youtube player config, videoId was: DFIJ0jB5IA4

### ISSUE THREAD

**Issue by harinikshan** [kotvertolet/youtube-jextractor#57]
While I am testing on android 10 version devices I am getting proper videoData but I I am running on oreo level devices I am getting "Cannot extract youtube player config" exceptions.
I am using the 0.3.3 version.
please check the issue

**Comment by lijinlj** [comment]
I am also facing same issue
`2020-12-04 13:53:22.515 29057-29148/com.sample.app W/System.err: com.github.kotvertolet.youtubejextractor.exception.ExtractionException: Extraction failed. Please, report here: https://github.com/kotvertolet/youtube-jextractor/issues. Error details: Cannot extract youtube player config, videoId was: c-jMjnVIc3E
2020-12-04 13:53:22.515 29057-29148/com.sample.app W/System.err:     at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extractYoutubePlayerConfig(YoutubeJExtractor.java:201)
2020-12-04 13:53:22.515 29057-29148/com.sample.app W/System.err:     at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extractYoutubeVideoData(YoutubeJExtractor.java:178)
2020-12-04 13:53:22.515 29057-29148/com.sample.app W/System.err:     at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extractAndPrepareVideoData(YoutubeJExtractor.java:149)
2020-12-04 13:53:22.516 29057-29148/com.sample.app W/System.err:     at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extract(YoutubeJExtractor.java:85)`

**Comment by kotvertolet** [comment]
@harinikshan I'm struggling to reproduce your issue, could you please tell me what API level did you used?

**Comment by harinikshan** [comment]
![IMG-20201204-WA0011](https://user-images.githubusercontent.com/28983765/101238859-187cd680-3709-11eb-986b-a7b04d0bf20c.jpg)

**Comment by harinikshan** [comment]
I think redmi devices have the problems I have checked with redmi note 8 also same issue.

**Comment by harinikshan** [comment]
I checked another OnePlus device with android 10 version It working fine I think its not the api level issue it may the parsing the data using issue.

**Comment by ki-erp** [comment]
![WhatsApp Image 2020-12-05 at 3 47 26 PM](https://user-images.githubusercontent.com/75432395/101240435-6992c780-3715-11eb-8fad-0bb2dc119681.jpeg)

We are facing the same issue, Admin please help ASAP.

**Comment by niteshfel** [comment]
Error details: Cannot extract youtube player config, videoId was: IC7kXsnYCWk
Same issue with me

**Comment by graffiti75** [comment]
I am also facing the same issue.

**Comment by niteshfel** [comment]
@kotvertolet Any update on this issue?

**Comment by niteshfel** [comment]
2020-12-18 10:53:19.716 12678-12848/com.tutorgrow.example W/System.err: com.github.kotvertolet.youtubejextractor.exception.ExtractionException: Extraction failed. Please, report here: https://github.com/kotvertolet/youtube-jextractor/issues. Error details: Cannot extract youtube player config, videoId was: IC7kXsnYCWk
2020-12-18 10:53:19.717 12678-12848/com.tutorgrow.example W/System.err:     at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.d(SourceFile:201)
2020-12-18 10:53:19.717 12678-12848/com.tutorgrow.example W/System.err:     at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.e(SourceFile:178)
2020-12-18 10:53:19.717 12678-12848/com.tutorgrow.example W/System.err:     at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.c(SourceFile:149)
2020-12-18 10:53:19.717 12678-12848/com.tutorgrow.example W/System.err:     at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extract(SourceFile:95)
2020-12-18 10:53:19.718 12678-12848/com.tutorgrow.example W/System.err:     at com.fel.example.student.view.activity.batch.StudyMaterialDocumentsStudentActivity$o.a(SourceFile:803)
2020-12-18 10:53:19.718 12678-12848/com.tutorgrow.example W/System.err:     at com.fel.example.student.view.activity.batch.StudyMaterialDocumentsStudentActivity$o.doInBackground(SourceFile:790)
2020-12-18 10:53:19.718 12678-12848/com.tutorgrow.example W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:378)
2020-12-18 10:53:19.718 12678-12848/com.tutorgrow.example W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-12-18 10:53:19.718 12678-12848/com.tutorgrow.example W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
2020-12-18 10:53:19.718 12678-12848/com.tutorgrow.example W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-12-18 10:53:19.719 12678-12848/com.tutorgrow.example W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-12-18 10:53:19.719 12678-12848/com.tutorgrow.example W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-12-18 10:53:19.727 12678-12776/com.tutorgrow.example D/EGL_emulation: eglMakeCurrent: 0xdd9c3900: ver 2 0 (tinfo 0xdd9ea170)
2020-12-18 10:53:19.795 12678-12691/com.tutorgrow.example I/torgrow.exampl: Background young concurrent copying GC freed 19169(1562KB) AllocSpace objects, 3(2360KB) LOS objects, 36% free, 6730KB/10MB, paused 1.314ms total 120.687ms
2020-12-18 10:53:19.831 12678-12776/com.tutorgrow.example D/EGL_emulation: eglMakeCurrent: 0xdd9c3900: ver 2 0 (tinfo 0xdd9ea170)

**Comment by tijot123** [comment]
i had done and added a pull request for the changes but he is not merging it

**Comment by antonyhaman** [comment]
@tijot123 Sorry for the delay, I had health issues, wasn't unable to support the library. I saw you made a lot of PR's, if you want to help me support the library I can give you the rights to do so.

**Comment by tijot123** [comment]
@kotvertolet no issues bro . take care .. now its working right..so will see afterwards
